package:
  name: cavpp_image_rename_and_convert
  version: [VERNUM]

source:
  git_tag: [VERNUM]
  git_url: https://github.com/cavpp/image_rename_and_convert.git [py34]

build:
  number: [BUILDNUM]
  string: a
  entry_points:
    - renameimages = rename_files.batch_renamer:main

requirements:
  build:
    - python
    - setuptools
    - pillow

  run:
    - python >=3.4
    - pyqt <=5.0
    - pillow

test:
  imports:
    - rename_files

  commands:
    - renameimages -h

about:
  home: https://github.com/cavpp/image_rename_and_convert
  license: GLP
  summary: "Renames and converts images into CAVPP/CAPS naming and specs."

app:
  entry: renameimages --gui
  summary: Renames and converts images into CAVPP/CAPS naming and specs.
